### ISSUE TITLE
Doesn't support new Docker `image` syntax

### ISSUE THREAD

**Issue by smcelhinney** [prisma-labs/serverless-plugin-typescript#227]
As per https://www.serverless.com/blog/container-support-for-lambda, you can now use the `image` property in function instead of a `handler`. 

Error 
```typescript
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'split' of undefined
```
is thrown at https://github.com/prisma-labs/serverless-plugin-typescript/blob/master/src/typescript.ts#L51 because it expects a `handler` property to be defined

**Comment by smcelhinney** [comment]
If you've found this issue from a search engine, a (less-than-ideal) solution I've used for deployment is to create a separate `serverless.docker.yml` file with your Docker based deployments, and run `serverless deploy -c serverless.docker.yml`

**Comment by alanwilter** [comment]
Sorry, I found this issue by search... and I was doing, presumably, exactly what you said, yet, this not working for me:

Test based on [example](https://github.com/serverless/serverless-plugin-typescript/tree/master/example) (which is awfully outdated).

`Dockerfile`:

```docker
FROM public.ecr.aws/lambda/nodejs:14
COPY handler.ts ./
CMD ["handler.hello"]
```

`serverlessD.yml`:

```yml
service: serverless-example
frameworkVersion: "2 || 3"
plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  # runtime: nodejs14.x
  ecr:
    images:
      appimage:
        path: ./
  region: eu-west-2
  lambdaHashingVersion: 20201221

functions:
  hello:
    # handler: handler.hello
    image:
      name: appimage
    events:
      - http:
          path: hello
          method: get
```

Then:
```bash
$ sls deploy -s test -c serverlessD.yml

Serverless: Compiling with Typescript...
 
 Type Error ----------------------------------------------
 
  TypeError: Cannot read property 'split' of undefined
...
```

What am I doing wrong please?
